#!/usr/bin/env python   
from os.path import isfile, basename, splitext
from clusteralign.options import parse
from clusteralign.alignment import Alignment


def run(basefile, args, error):
    if not isfile(basefile):
        error("no such file: %s" % basefile)

    (basefilename, basefileext) = splitext(basename(basefile))
    msffile = basefilename + ".msf"

    a = Alignment(basefile, **args)
    a.output()
    a.write(msffile)

if __name__ == '__main__':
    args, error = parse(allow_verbose=True, multiprocessing=True)

    basefile = args.files[0]
    del args.files

    run(basefile, vars(args), error)
